### ISSUE TITLE
redis-ruby instance not installed

### ISSUE THREAD

**Issue by joesun99** [itsmetommy/docker-redis-cluster#1]
After installing I get following error on docker-compose logs redis-ruby:

"redis-ruby    | standard_init_linux.go:190: exec user process caused "no such file or directory"

**Comment by itsmetommy** [comment]
Are you using a windows computer? If so, I found an existing issue with line-ending auto conversion https://github.com/bigchaindb/bigchaindb/issues/2215. Maybe try deleting the old cloned directory and clone the repo using --config core.autocrlf=input.

Example:
git clone https://github.com/itsmetommy/docker-redis-cluster.git --config core.autocrlf=input

**Comment by joesun99** [comment]
Hi.

Thx for the quick response. Yes i am working on windows with docker linux containers. It is working now.

Regards

**Comment by itsmetommy** [comment]
Was the issue solved by using the option core.autocrlf=input? I wanted to confirm just in case another user had the same issue.

**Comment by itsmetommy** [comment]
Closing issue.
