### ISSUE TITLE
Testing cluster node failure

### ISSUE THREAD

**Issue by juborto** [itsmetommy/docker-redis-cluster#4]
Hi Tommy,
thanks for your post, very useful!
I had a question regarding a node failure. I was trying to test that with my spring application to check if the reconnection was working.

I removed one node from the cluster
```
$ docker rm -f docker-redis-cluster_redis-3_1
docker-redis-cluster_redis-3_1
```
And I recreate it here with the same script

```
$ docker-compose up --build -d
[...]
Successfully built c42043755120
Successfully tagged redis-cluster-node:latest
docker-redis-cluster_redis-2_1 is up-to-date
docker-redis-cluster_redis-1_1 is up-to-date
docker-redis-cluster_redis-5_1 is up-to-date
docker-redis-cluster_redis-6_1 is up-to-date
docker-redis-cluster_redis-4_1 is up-to-date
Creating docker-redis-cluster_redis-3_1 ... done
Recreating docker-redis-cluster_redis-cluster_1 ... done
```

The container redis-3_1 is recreated but it seems that it is not able to join the cluster

```
$ docker exec -ti docker-redis-cluster_redis-1_1 redis-cli -c -p 7001
127.0.0.1:7001> cluster nodes
07c0d54474fa1f1b1737858eca1adb859506e993 10.0.0.14:7004@17004 master - 0 1593791005526 7 connected 10923-16383
162ddfc067889991e8baa8712eb1cb1c8e08f9b7 :0@0 master,fail,noaddr - 1593790908571 1593790906000 3 disconnected
1c5e4ede11e1bbd433f36722670fbfde5c494cd7 10.0.0.15:7005@17005 slave c9370a7af12682bcd1968ce1fdd2b411ad929ba6 0 1593791005526 5 connected
90477f14193fc52596f8f89b6f972e059b368624 10.0.0.16:7006@17006 slave d94176d618dc57c0be1b0eda49d22d1af97b1197 0 1593791005927 2 connected
c9370a7af12682bcd1968ce1fdd2b411ad929ba6 10.0.0.11:7001@17001 myself,master - 0 1593791004000 1 connected 0-5460
d94176d618dc57c0be1b0eda49d22d1af97b1197 10.0.0.12:7002@17002 master - 0 1593791004924 2 connected 5461-10922
```

```
$ docker logs docker-redis-cluster_redis-cluster_1
[ERR] Node 10.0.0.11:7001 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.
```

Do you have an idea how to solve this situation? Loosing one node, recreating it and adding it back to the cluster.
Thanks for your help,
J.

**Comment by itsmetommy** [comment]
Try the following steps.

Build and start.

`docker-compose up --build -d`

View nodes.

`docker exec -it docker-redis-cluster_redis-1_1 redis-cli -p 7001 cluster nodes`

Remove node.

`docker rm -f docker-redis-cluster_redis-3_1`

View nodes. You should see the failed node.

`docker exec -it docker-redis-cluster_redis-1_1 redis-cli -p 7001 cluster nodes`

Build and start to re-create the failed node.

`docker-compose up --build -d`

Add node as slave back into cluster.

`docker exec -it docker-redis-cluster_redis-1_1 redis-cli -p 7001 --cluster add-node 10.0.0.13:7003 10.0.0.11:7001 --cluster-slave`

View nodes and note down failed node id.

`docker exec -it docker-redis-cluster_redis-1_1 redis-cli -p 7001 cluster nodes`

Remove failed node from cluster using its node id.

`docker exec -it docker-redis-cluster_redis-1_1 redis-cli -p 7001 CLUSTER FORGET 9f12c24bd768174c6812a81e1ccc502e9a53aa6b`

View nodes and verify that the failed node has been removed.

`docker exec -it docker-redis-cluster_redis-1_1 redis-cli -p 7001 cluster nodes`

**Comment by juborto** [comment]
Thanks for your quick reply! I will test with these commands.
